### ISSUE TITLE
Exception: invalid file on valid UTF-8 strings file

### ISSUE THREAD

**Issue by postmechanical** [dulaccc/igenstrings#1]
INFO:root:Running the script on path <path>
languages found ['<path>/en.lproj']
iconv: <path>/en.lproj/Localizable.strings: No such file or directory
DEBUG:root:"Czech" = "Tchèque";

DEBUG:root:2 
ERROR:root:Line 2 of file '<path>/en.lproj/Localizable.strings.old' raising the exception: 
ERROR:root:Error: input files have invalid format.
Traceback (most recent call last):
  File "~/bin/pygenstrings-master/genstring.py", line 264, in <module>
    localize(opts.path, opts.excluded_paths)
  File "~/bin/pygenstrings-master/genstring.py", line 216, in localize
    merge(merged, old, new)
  File "~/bin/pygenstrings-master/genstring.py", line 180, in merge
    old = LocalizedFile(old_fname, auto_read=True)
  File "~/bin/pygenstrings-master/genstring.py", line 82, in __init__
    self.read_from_file(fname)
  File "~/bin/pygenstrings-master/genstring.py", line 128, in read_from_file
    raise Exception('invalid file')
Exception: invalid file

**Comment by dulaccc** [comment]
I know it's been forever @postmechanical, but the project now has been completed rewritten. There is unit tests covering all the code base now and the command line is available as pypi package.

Cheers
